### ISSUE TITLE
Shifting permission to DHU students

### ISSUE THREAD

**Issue by erickguan** [DHUers/0-meta#1]
@wujysh I am intend to transfer admin permissions to my classmates @Cathon. I would remove us from admin. Please confirm this change.

**Comment by erickguan** [comment]
I will change both of us as outside collabaorator. It's fine to opt-out at any time.
As it should, we would lose any permissions after that point. I would trust him for his decision ever since.

**Comment by wujysh** [comment]
OK. I agree.

**Comment by erickguan** [comment]
🎓🎓🎓
